# Generated by Django 3.2.16 on 2023-01-17 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام بلاگ')),
                ('text', models.TextField(verbose_name='متن بلاگ')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ثبت')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ و ساعت ویرایش')),
                ('status', models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], max_length=3)),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
