# Generated by Django 3.2.16 on 2023-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_postblog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], max_length=3, verbose_name='وضعیت'),
        ),
    ]
